[2023-07-05T13:44:06.387+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:06.401+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:44:06.416+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.416+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:06.657+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.636+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:44:06.667+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.663+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:44:06.674+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.673+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:44:06.703+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:07.775+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:07.772+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:exercise17
[2023-07-05T13:44:07.826+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:07.825+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:exercise17
[2023-07-05T13:44:07.864+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:07.864+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:exercise17
[2023-07-05T13:44:07.967+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:07.963+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:44:08.106+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:08.106+0000] {dag.py:2747} INFO - Creating ORM DAG for exercise17
[2023-07-05T13:44:08.201+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:08.201+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:44:08.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 1.989 seconds
[2023-07-05T13:44:44.793+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:44.799+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:44:44.810+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:44.810+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:44.870+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:44.867+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:44:44.881+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:44.879+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:44:44.887+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:44.886+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:44:44.898+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:45.010+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:45.009+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:44:45.297+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:45.296+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:44:45.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.768 seconds
[2023-07-05T13:45:17.685+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:17.691+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:45:17.703+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:17.701+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:17.774+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:17.772+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:45:17.781+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:17.780+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:45:17.788+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:17.787+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:45:17.806+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:19.172+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:19.166+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:45:19.320+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:19.319+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:45:19.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 1.904 seconds
[2023-07-05T13:45:50.524+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:50.530+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:45:50.540+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:50.615+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.612+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:45:50.618+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.618+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:45:50.624+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.623+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:45:50.638+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:50.738+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.738+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:45:50.788+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:50.788+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:45:50.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.307 seconds
[2023-07-05T13:46:21.169+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:21.171+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:46:21.175+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.175+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:21.194+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.193+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:46:21.198+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.198+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:46:21.201+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.201+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:46:21.205+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:21.243+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.242+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:46:21.278+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:21.278+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:46:21.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.139 seconds
[2023-07-05T13:46:51.419+0000] {processor.py:157} INFO - Started process (PID=128) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:51.422+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:46:51.426+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.425+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:51.446+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.445+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:46:51.450+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.449+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:46:51.453+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.453+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:46:51.459+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:51.501+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.500+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:46:51.537+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:51.537+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:46:51.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.152 seconds
[2023-07-05T13:47:21.724+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:21.727+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:47:21.733+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:21.733+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:21.761+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:21.759+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:47:21.765+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:21.764+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:47:21.771+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:21.770+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:47:21.776+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:21.978+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:21.977+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:47:22.076+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:22.076+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:47:22.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.411 seconds
[2023-07-05T13:47:52.242+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:52.245+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:47:52.250+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.249+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:52.272+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.271+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:47:52.276+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.276+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:47:52.280+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.279+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:47:52.284+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:52.324+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.324+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:47:52.358+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:52.358+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:47:52.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.148 seconds
[2023-07-05T13:48:22.473+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:22.478+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:48:22.482+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.481+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:22.501+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.500+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:48:22.504+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.504+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:48:22.507+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.507+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:48:22.512+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:22.555+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.554+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:48:22.590+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:22.590+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:48:22.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.148 seconds
[2023-07-05T13:48:53.119+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:53.146+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:48:53.152+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.152+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:53.182+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.179+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:48:53.185+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.185+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:48:53.188+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.187+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:48:53.193+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:48:53.296+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.295+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:48:53.358+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:48:53.358+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:48:53.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.311 seconds
[2023-07-05T13:49:24.082+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:24.085+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:49:24.091+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.090+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:24.120+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.119+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:49:24.131+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.130+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:49:24.135+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.135+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:49:24.140+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:24.179+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.178+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:49:24.214+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:24.214+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:49:24.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.161 seconds
[2023-07-05T13:49:54.634+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:54.637+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:49:54.642+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.641+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:54.666+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.665+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:49:54.670+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.669+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:49:54.672+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.672+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:49:54.678+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:49:54.720+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.719+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:49:54.756+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:49:54.756+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:49:54.782+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.153 seconds
[2023-07-05T13:50:25.131+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:25.135+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:50:25.141+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.141+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:25.170+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.169+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:50:25.175+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.174+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:50:25.182+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.181+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:50:25.188+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:25.251+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.250+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:50:25.298+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:25.298+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:50:25.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.211 seconds
[2023-07-05T13:50:56.036+0000] {processor.py:157} INFO - Started process (PID=263) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:56.057+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:50:56.063+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.063+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:56.118+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.114+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:50:56.126+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.126+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:50:56.131+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.130+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:50:56.150+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:50:56.241+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.239+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:50:56.304+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:50:56.304+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:50:56.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.316 seconds
[2023-07-05T13:51:26.490+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:26.496+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:51:26.501+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.501+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:26.523+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.522+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:51:26.526+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.526+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:51:26.530+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.530+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:51:26.539+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:26.582+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.582+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:51:26.618+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:26.618+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:51:26.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.158 seconds
[2023-07-05T13:51:56.935+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:56.938+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:51:56.943+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:56.942+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:56.964+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:56.962+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:51:56.966+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:56.966+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:51:56.969+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:56.969+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:51:56.973+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:51:57.015+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:57.013+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:51:57.055+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:51:57.055+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:51:57.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.151 seconds
[2023-07-05T13:52:27.281+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:27.284+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:52:27.291+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.290+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:27.312+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.310+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:52:27.316+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.316+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:52:27.319+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.319+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:52:27.324+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:27.369+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.369+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:52:27.403+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:27.402+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:52:27.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.152 seconds
[2023-07-05T13:52:57.496+0000] {processor.py:157} INFO - Started process (PID=331) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:57.499+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:52:57.505+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.504+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:57.529+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.527+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:52:57.533+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.532+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:52:57.537+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.536+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:52:57.542+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:52:57.589+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.589+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:52:57.628+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:52:57.628+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:52:57.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.174 seconds
[2023-07-05T13:53:28.448+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:28.451+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:53:28.456+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.456+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:28.477+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.476+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:53:28.480+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.480+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:53:28.482+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.482+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:53:28.486+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:28.527+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.526+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:53:28.561+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:28.561+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:53:28.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.145 seconds
[2023-07-05T13:53:58.727+0000] {processor.py:157} INFO - Started process (PID=365) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:58.733+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:53:58.738+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:58.766+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.764+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:53:58.773+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.772+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:53:58.777+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.777+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:53:58.783+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:53:58.828+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.827+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:53:58.865+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:53:58.865+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:53:58.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.171 seconds
[2023-07-05T13:54:29.012+0000] {processor.py:157} INFO - Started process (PID=382) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:54:29.015+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:54:29.021+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.021+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:54:29.042+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.041+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:54:29.044+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.044+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:54:29.047+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.046+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:54:29.051+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:54:29.093+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.092+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:54:29.138+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:54:29.138+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:54:29.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.156 seconds
[2023-07-05T13:55:00.012+0000] {processor.py:157} INFO - Started process (PID=399) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:00.017+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:55:00.023+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.023+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:00.045+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.043+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:55:00.047+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.047+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:55:00.050+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.050+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:55:00.054+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:00.095+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.095+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:55:00.129+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:00.129+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:55:00.155+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.150 seconds
[2023-07-05T13:55:24.697+0000] {processor.py:157} INFO - Started process (PID=413) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:24.700+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:55:24.704+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:24.704+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:24.711+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:24.711+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/exercise17.py assumed to contain no DAGs. Skipping.
[2023-07-05T13:55:24.712+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:24.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.044 seconds
[2023-07-05T13:55:55.129+0000] {processor.py:157} INFO - Started process (PID=431) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:55.133+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:55:55.137+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:55.137+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:55.143+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:55:55.142+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/exercise17.py assumed to contain no DAGs. Skipping.
[2023-07-05T13:55:55.145+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:55:55.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.041 seconds
[2023-07-05T13:56:25.232+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:25.236+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:56:25.239+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:56:25.239+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:25.255+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:56:25.254+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/exercise17.py assumed to contain no DAGs. Skipping.
[2023-07-05T13:56:25.265+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:25.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.080 seconds
[2023-07-05T13:56:55.428+0000] {processor.py:157} INFO - Started process (PID=466) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:55.431+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:56:55.433+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:56:55.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:55.438+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:56:55.437+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/exercise17.py assumed to contain no DAGs. Skipping.
[2023-07-05T13:56:55.439+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:56:55.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.036 seconds
[2023-07-05T13:57:25.567+0000] {processor.py:157} INFO - Started process (PID=483) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:57:25.570+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:57:25.572+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:57:25.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:57:25.577+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:57:25.576+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/exercise17.py assumed to contain no DAGs. Skipping.
[2023-07-05T13:57:25.578+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:57:25.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.035 seconds
