[2023-07-05T14:34:20.260+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opensky_data_dag.write_to_json manual__2023-07-05T14:33:52.965789+00:00 [queued]>
[2023-07-05T14:34:20.275+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opensky_data_dag.write_to_json manual__2023-07-05T14:33:52.965789+00:00 [queued]>
[2023-07-05T14:34:20.276+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-05T14:34:20.295+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): write_to_json> on 2023-07-05 14:33:52.965789+00:00
[2023-07-05T14:34:20.302+0000] {standard_task_runner.py:57} INFO - Started process 372 to run task
[2023-07-05T14:34:20.307+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'opensky_data_dag', 'write_to_json', 'manual__2023-07-05T14:33:52.965789+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/reading.py', '--cfg-path', '/tmp/tmpts3_b8jw']
[2023-07-05T14:34:20.309+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask write_to_json
[2023-07-05T14:34:20.384+0000] {task_command.py:410} INFO - Running <TaskInstance: opensky_data_dag.write_to_json manual__2023-07-05T14:33:52.965789+00:00 [running]> on host 69463eb32c6a
[2023-07-05T14:34:20.514+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='opensky_data_dag' AIRFLOW_CTX_TASK_ID='write_to_json' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T14:33:52.965789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-05T14:33:52.965789+00:00'
[2023-07-05T14:34:20.516+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reading.py", line 43, in write_to_json
    output_dir = os.path.dirname(os.path.abspath(_file_))
NameError: name '_file_' is not defined
[2023-07-05T14:34:20.535+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=opensky_data_dag, task_id=write_to_json, execution_date=20230705T143352, start_date=20230705T143420, end_date=20230705T143420
[2023-07-05T14:34:20.552+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task write_to_json (name '_file_' is not defined; 372)
[2023-07-05T14:34:20.600+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-05T14:34:20.625+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
